# Generated by Django 2.2.5 on 2019-10-11 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('loginPW', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('loginID', models.CharField(max_length=20, verbose_name='학번')),
                ('usernumber', models.CharField(max_length=64, verbose_name='전화번호1')),
                ('usernumber2', models.CharField(max_length=64, verbose_name='전화번호2')),
            ],
            options={
                'verbose_name_plural': '동국푸드 유저',
                'db_table': 'DGFOOD_partner',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='업체 이름')),
                ('contact', models.CharField(max_length=50, verbose_name='연락처')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('description', models.TextField(verbose_name='상세 소개')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '동국푸드 업체',
                'db_table': 'DGFOOD_store',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='메뉴 이미지')),
                ('name', models.CharField(max_length=50, verbose_name='메뉴 이름')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Store')),
            ],
            options={
                'verbose_name_plural': '동국푸드 메뉴',
                'db_table': 'DGFOOD_menu',
            },
        ),
    ]
